# Generated by Django 4.2.7 on 2023-11-26 19:05

from django.db import migrations

def forwards(apps, schema_editor):
    TenantModel = apps.get_model("tenants.Tenant")
    TenantModel.objects.create(name="Tenant 1", domain_name="tenant1.com", database_name="tenant1")
    TenantModel.objects.create(name="Tenant 2", domain_name="tenant2.com", database_name="tenant2")


def backwards(apps, schema_editor):
    TenantModel = apps.get_model("tenants.Tenant")
    TenantModel.objects.filter(database_name__in=("tenant1", "tenant2")).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
